# Generated by Django 4.2.20 on 2025-09-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LostnFound', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='Categories',
        ),
        migrations.AddField(
            model_name='messages',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LostnFound.listing'),
        ),
    ]
