# Generated by Django 4.2.20 on 2025-09-29 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LostnFound', '0002_rename_category_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='When',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
