# Generated by Django 4.2.20 on 2025-10-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostnFound', '0003_messages_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Found',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='LastKnown',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='When',
        ),
    ]
