# Generated by Django 4.2.20 on 2025-10-02 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LostnFound', '0004_remove_listing_found_remove_listing_lastknown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='When',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
