# Generated by Django 4.2.20 on 2025-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostnFound', '0006_remove_messages_foundimage_messages_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='Attachment',
        ),
        migrations.AddField(
            model_name='messages',
            name='FoundImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Desc',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Image',
            field=models.URLField(),
        ),
    ]
