# Generated by Django 4.2.20 on 2025-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostnFound', '0007_remove_messages_attachment_messages_foundimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='FoundImage',
        ),
        migrations.AddField(
            model_name='messages',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
